M48
; DRILL file {KiCad 9.0.5} date 2026-04-19T15:40:40-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-19T15:40:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.460
%
G90
G05
T1
X132.0Y-104.0
T2
X106.51Y-95.62
X106.51Y-104.38
X143.49Y-95.62
X143.49Y-104.38
M30
